import time
from config import db

def clear_synthetic_deliveries():
    print("\n[CLEANUP INITIALIZED] - Scanning for synthetic load test data...")
    deliveries_ref = db.collection('deliveries')
    
    docs_to_delete = []
    
    # We iterate through the stream since Firestore doesn't directly support substring queries natively
    for doc in deliveries_ref.stream():
        data = doc.to_dict()
        pickup_address = data.get('pickup_loc', {}).get('address', '')
        
        # Check if the document was artificially generated by the load_tester script
        if "Load Test Pickup Route" in pickup_address:
            docs_to_delete.append(doc.reference)
            
    if not docs_to_delete:
        print("No synthetic load test deliveries found. Database is clean!")
        return
        
    print(f"Found {len(docs_to_delete)} synthetic deliveries. Initiating batch deletion...\n")
    
    # Firestore batches support a maximum of 500 operations per batch block
    deleted_count = 0
    batch = db.batch()
    
    for doc_ref in docs_to_delete:
        batch.delete(doc_ref)
        deleted_count += 1
        
        # Commit and reset the batch cleanly every 500 records
        if deleted_count % 500 == 0:
            batch.commit()
            batch = db.batch() 
            
    # Commit any remaining docs in the final batch buffer
    if deleted_count % 500 != 0:
        batch.commit()
        
    print(f"[CLEANUP SUCCESS] - Safely purged {deleted_count} load test deliveries from Firestore!\n")

if __name__ == "__main__":
    start_time = time.time()
    clear_synthetic_deliveries()
    print(f"Execution Time: {(time.time() - start_time):.2f} seconds")
